# Generated by Django 4.1.7 on 2023-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_uploadimage_alter_comment_id_alter_following_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='following_user',
            field=models.IntegerField(),
        ),
    ]
